engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 36
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"
ratings:
  paths:
  - "**.py"
exclude_paths: []
