engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "B"
ratings:
  paths:
  - "**.py"
exclude_paths: []
