language: python

branches:
    only:
        - master
matrix:
    include:
        - python: 2.7 --process-dependency-links --allow-all-external
        - python: 3.6 --process-dependency-links --allow-all-external
install:
    - pip install .
    - pip install flake8

script:
    - flake8
