language: python
python:
- '2.7'
- '3.6'
install:
- pip install
- pip install .
- pip install flake8
script:
- flake8
deploy:
  provider: pypi
  skip_existing: true
  user: tparker
  password:
    secure: fnUScOfBmOsZUnB55osg2AisEJgxEcutFapktL1s/N21gdWMY36BPWDCK/4eyhsz45EcL5zHOTf+0wT5Bgc+Kxl/m7Q/Esg0sBT+7i9wt+HE5tdgpt/zZrBUwvj9bPmsJOexWMycOsSV2uKLzi0tE3J2nmc2dY4reuWGGf8znROJLnBbdkY5DpsVJY7dSwiO5A9MohjBuFlowKC8FQ1bZWo+ND4RkU7fPvwVUUTjZCfonjAZhPJst2tIJmxOpVrAhjB+QSpNbp3cBwj8E2FOLA+Hu8oNUUPsFYjhCKgCxPN/0JAQ5y0eYu1lFbhSZLLg+yRdvQIat+JvbtieyD/4uyUS4+0u+XDzow4unMyerIz6OBP7ED8kwoChpb2KBR4q65fBxqa4vpKGCcjUHG8nmCmVs2NZzgckhw95TYEe9ImxLysoMy0cZK8pzj6XPV3KOKCpEiSLNzgF/+NJqOkohcYi9JFYezbThgWDssT2gVpvABiIByYbe3K6j2y/oyhJOEYuuZnFwsi7QxfQmseGqo6CBbn1NVCWq8qPsyok/uzn9DHILgw0HnkaPfpJsftNzCkLPupPRHc2ritU4Z1nLtov9Sf0UjbpkX+wllMhlZEnNfq7MRThCu3rn39qp3MULQakbyM6QxMzZe0S/YQ3BMRTf2UfAq+TU5a/FkZXWFo=
  on:
    tags: true
